### ISSUE TITLE
local variable 'res' referenced before assignment

### ISSUE THREAD

**Issue by zanac** [florianholzapfel/panasonic-viera#28]
for now solved using "try catch" ;)
it seems that when i shutdown the tv for some seconds if i call the api the tv while shotting down give some problems....

Exception Type: | UnboundLocalError
local variable 'res' referenced before assignment
panasonic_viera/__init__.py in _request_session_id, line 412

**Comment by boisei0** [comment]
https://github.com/florianholzapfel/panasonic-viera/blob/master/panasonic_viera/__init__.py#L404-L412
It appears to be caused by an HTTP error being catched, but it not being a 500 error, so the function continues below and `res` does indeed not exist. For further debugging, could you add a some logging inside the `except HTTPError as e` block, to figure out what the `e` object is like and what code is given rather than 500.

**Comment by ramondunker** [comment]
@zanac How did you solve this?

**Comment by millst** [comment]
the error code is 403 - Forbidden


403
Traceback (most recent call last):
  File "bob.py", line 4, in <module>
    rc.request_pin_code()
  File "/volume1/web/current-rms/panasonic-viera-master/panasonic_viera/__init__.py", line 331, in request_pin_code
    root = ET.fromstring(res)
UnboundLocalError: local variable 'res' referenced before assignment

**Comment by stones18** [comment]
Looked with Wireshark, one difference between my handmade packet and the python script is:
Connection close and not keep-alive
I'm new in python think it could be fixed maybve with urllib3

**Comment by stones18** [comment]
Problem here was same, because Server was in another IP subnet.
